gksek015/onson

package.json
src/components/chatbox/ChatBoxButton.tsx
yarn.lock

바텀 위치의 gnb 고려한 플로팅 버튼 위치 조정 완료.

style: 플로팅 버튼 위치 조정

---

next.config.mjs
src/api/getPosts.ts
src/app/page.tsx
src/app/search-list/_components/Adress.tsx
src/app/search-list/page.tsx
src/components/home/MainPage.tsx
src/components/home/VolunteerCard.tsx

게시글 리스트 완성 및 id받아서 디테일 페이지로 넘어가게 구현 완료
어떤 변경 사항이 있나요?

feat: 게시글 리스트 완성 및 id받아서 디테일 페이지로 넘어가게 구현 완료

---

src/components/chatbox/chatUI/Chatroom.tsx
src/components/home/VolunteerCard.tsx

피드백 반영해서  불필요한 div 삭제 했습니다,
어떤 변경 사항이 있나요?

fix: 불필요한 div 삭제

---

package.json
src/lib/actions/auth/action.ts
src/utils/store/userStore.ts
yarn.lock

feat & fix : zustand를 통한 상태관리 구현 및 관련된 부분 수정

---

src/app/detail/[id]/_components/PostContent.tsx
src/app/detail/[id]/_components/PostTags.tsx

fix: 충돌 해결

---

src/app/detail/[id]/_components/BookmarkButton.tsx
src/app/detail/[id]/_components/Header.tsx
src/components/icons/Icons.tsx
src/hooks/useGetPostById.ts
src/lib/posts/updatePost.ts

모집 마감, 해제 기능 구현 완료
어떤 변경 사항이 있나요?

feat: 모집 마감, 해제 기능 구현 완료

---

src/app/(auth)/login/_components/LoginForm.tsx
src/app/(auth)/login/page.tsx
src/app/(auth)/my-page/_components/MyBookmarks.tsx
src/app/(auth)/my-page/_components/UserInfo.tsx
src/app/(auth)/my-page/bookmarks/page.tsx
src/app/(auth)/my-page/page.tsx
src/app/(auth)/reset-password/_components/ResetPwForm.tsx
src/app/(auth)/reset-password/page.tsx
src/app/detail/[id]/_components/PostContent.tsx
src/app/detail/[id]/_components/PostTags.tsx
src/app/globals.css
src/app/page.tsx
src/components/auth/InitializeUser.tsx
src/components/home/MainSection.tsx
src/components/layout/header-right/ProfileDropdown.tsx
src/lib/actions/auth/action.ts
src/utils/store/userStore.ts
src/utils/supabase/middleware.ts

로그인 부분 수정하였습니다. 
로그아웃시에 세션이 완전히 삭제 안되는 버그가 있습니다.
세션이 다 안날라가면 다시 로그아웃을 한번 더 눌러주세요
어떤 변경 사항이 있나요?

fix & feat : 로그인 세션관리 수정 및 마이페이지 작업중

---

src/components/chatbox/ChatBoxModal.tsx
src/components/chatbox/ai/AIChatroom.tsx

bottomNav 부분 수정 완료
어떤 변경 사항이 있나요?

fix: bottomNav 부분 수정 완료

---

src/app/(auth)/sign-up/_components/SignUpForm.tsx
src/app/(auth)/sign-up/page.tsx

회원가입 버튼, 뒤로가기 버튼 css 변경했습니다.
어떤 변경 사항이 있나요?

style : 회원가입 버튼, 뒤로가기 버튼 css 변경

---

src/app/(auth)/_components/AuthInput.tsx
src/lib/actions/auth/action.ts

1. 로그인, 닉네임 수정 등에 사용되는 서버액션에서 
세션 체크시 서버 콘솔 에러가 발생 하는 부분 수정하였습니다. 
2. AuthInput 컴포넌트에서 불필요한 displayName 객체를 
사용하는 부분을 수정하였습니다. 
어떤 변경 사항이 있나요?

fix : 서버 액션, AuthInput 수정

---

src/app/create/_components/NewPostComp.tsx
src/app/list/_components/AllLists.tsx
src/app/post-update/_components/UpdatePostComp.tsx
src/components/common/Loading.tsx
src/components/home/MainSection.tsx

페이지 넘어갈 때 로딩 구현 완료했습니다.
어떤 변경 사항이 있나요?

Feat/post : 로딩 구현

---

src/app/(auth)/my-page/_components/MyProfile.tsx
src/app/(auth)/my-page/_components/ProfileUpdate.tsx
src/lib/actions/auth/action.ts

프로필 수정, 마이페이지 이미지 등록 기능 구현 하였습니다. 
어떤 변경 사항이 있나요?

feat : 프로필 수정, 마이페이지 이미지 등록 기능 구현

---

src/app/detail/[id]/_components/Header.tsx
src/app/detail/[id]/_components/PostContent.tsx
src/app/detail/[id]/_components/PostDetail.tsx
src/app/detail/[id]/_components/PostTags.tsx
src/components/chatbox/ChatBoxButton.tsx
src/components/common/Loading.tsx
src/components/common/post/customCalendar.css
src/components/home/HeroSection.tsx

디자인 시안 반영 작업했습니다.
디테일 페이지 조금 수정했습니다.
로딩, 이미지 등 수정했습니다.
어떤 변경 사항이 있나요?

Feat/post : 디자인 시안 반영 작업

---

src/app/(auth)/sign-up/_components/SignUpForm.tsx
src/lib/actions/auth/action.ts

chore : 버그 테스트

---

src/components/chatbox/chatRoom/ChatMessage.tsx

맥북에서 챗팅시 두번 메시지 가는 부분 수정
어떤 변경 사항이 있나요?

fix : 맥북에서 챗팅시 두번 메시지 가는 부분 수정

---

src/components/chatbox/ai/AIChatbot.tsx
src/components/chatbox/chatRoom/ChatMessage.tsx
src/components/chatbox/chatUI/ModalHeader.tsx

챗봇 input창에 enter키 입력
어떤 변경 사항이 있나요?

feat:AI챗봇 인풋창 enter 입력

---

src/app/create/_components/NewPostComp.tsx
src/app/detail/[id]/_components/Header.tsx
src/components/home/VolunteerCard.tsx
src/components/home/VolunteerCardNoImg.tsx

글 등록후 리스트 페이지 이동 수정하였습니다. 
어떤 변경 사항이 있나요?

fix: 글 등록후 리스트 페이지 이동 수정

---

src/app/(auth)/my-page/_components/ProfileUpdate.tsx
src/lib/actions/auth/action.ts

1.프로필 이미지 수정 상태관리 변경
2.소셜 로그인시, 닉네임 unKnown으로 나오는 현상 수정
어떤 변경 사항이 있나요?

fix : UT 후, 수정사항 반영

---

src/app/(home)/MainSection.tsx
src/app/page.tsx
src/hooks/useInitializeUser.ts

initializeUser.tsx파일을 useInitializeUser.ts 훅으로 변경했습니다.
어떤 변경 사항이 있나요?

Feat/auth :  initializeUser.tsx파일을 useInitializeUser.ts 훅으로 변경

---

src/app/(home)/AddressButton.tsx
src/app/(home)/MainSection.tsx
src/app/list/_components/AllLists.tsx
src/app/list/_components/Tags.tsx
src/app/list/page.tsx
src/app/page.tsx
src/components/chatbox/ChatBoxModal.tsx
src/components/common/AddressSearch.tsx
src/components/layout/BottomNav.tsx
src/components/layout/Footer.tsx
src/components/layout/header/ChatIcon.tsx
src/components/layout/header/LeftSide.tsx
src/lib/auth/clientAuth.ts
src/utils/store/useGNBStore.ts
tailwind.config.ts

디테일에서 사용자 채팅 후 GNB 안나오던 버그 수정
전체적인 md 사용한 부분 mobile로 수정
어떤 변경 사항이 있나요?

Feat/chats 디테일에서 사용자 채팅 후 GNB 안나오던 버그 수정

---

src/app/(home)/MainSection.tsx
src/app/list/_components/AddressTags.tsx
src/app/list/_components/AllLists.tsx
src/app/page.tsx

fix : 태그 수정, gnb 수정
어떤 변경 사항이 있나요?

fix : 태그 수정, gnb 수정

---

src/components/chatbox/ChatBoxModal.tsx
src/components/chatbox/ai/AIChatbot.tsx
src/components/chatbox/chatRoom/ChatMessage.tsx

fix: 자동 스크롤 문제 해결

---

src/app/(auth)/my-page/_components/MyBookmarks.tsx
src/app/(auth)/my-page/_components/MyParticipants.tsx
src/app/(auth)/my-page/_components/MyPosts.tsx
src/app/(auth)/my-page/_components/QuickParticipants.tsx

마이페이지 부분 스타일 수정하였습니다. 
어떤 변경 사항이 있나요?

style : 마이페이지 스타일 수정

---

src/app/(auth)/my-page/_components/QuickParticipants.tsx
src/app/detail/[id]/_components/PostContent.tsx

디테일 페이지 드롭다운 css 수정
어떤 변경 사항이 있나요?

style: 드롭다운 css 수정

---

src/app/(auth)/my-page/_components/QuickParticipants.tsx
src/app/(auth)/sign-up/_components/SignUpForm.tsx
src/app/(home)/VolunteerCard.tsx
src/components/chatbox/ChatBoxModal.tsx

불필요한 주석 제거 및 데스크탑에서 로그인 쪽 모달이 열리도록 설정
어떤 변경 사항이 있나요?

feat:불필요한 주석 제거 및 데스크탑에서 로그인 쪽 모달이 열리도록 설정

---

src/app/(home)/AddressButton.tsx
src/app/list/_components/AddressTags.tsx
src/app/list/_components/CategoryButton.tsx
src/hooks/usePostForm.ts

데스크탑, 모바일 둘 다 비로그인 사용자 라우터 설정 홈으로 바꿨습니다.
어떤 변경 사항이 있나요?

Feat/post : 데스크탑 환경에서 비로그인 사용자 라우터 설정

---

src/app/(auth)/_components/Header.tsx
src/app/(auth)/my-page/_components/UserInfo.tsx
src/app/globals.css
src/lib/posts/getUserPosts.ts

마이페이지 1440기준으로 변경, 로그인, 회원가입등 하이드레이션 에러 수정
어떤 변경 사항이 있나요?

fix: 마이페이지 1440기준으로 변경, 로그인, 회원가입등 하이드레이션 에러 수정

---

src/components/chatbox/ChatBoxModal.tsx
src/components/chatbox/ClientChatModal.tsx
src/components/chatbox/chatRoom/ChatMessage.tsx
src/components/layout/BottomNav.tsx
src/utils/store/useModalStore.ts

간격 조절 및 각종 버그 수정
어떤 변경 사항이 있나요?

Feat/chats 간격 조절 및 각종 버그 수정

---

src/app/(auth)/my-page/_components/ProfileUpdate.tsx
src/app/(auth)/my-page/_components/UserInfo.tsx
src/app/(auth)/my-page/page.tsx

fix: 마이페이지 등 문구 수정

---

src/app/(auth)/sign-up/_components/SignUpForm.tsx

feat:회원가입 후 데스크탑은 모달로 이동
어떤 변경 사항이 있나요?

feat:회원가입 후 데스크탑은 모달로 이동

---

src/components/chatbox/ChatBoxModal.tsx
src/components/layout/BottomNav.tsx
src/utils/store/useModalStore.ts

fix: GNB 사라지는 버그수정

---

src/app/(auth)/sign-up/_components/SignUpForm.tsx
src/components/chatbox/ChatBoxModal.tsx
src/components/layout/BottomNav.tsx
src/utils/store/useModalStore.ts

최종 확인을 위한 merge입니다.
어떤 변경 사항이 있나요?

최종 확인을 위한 merge입니다.

---

src/app/(auth)/login/_components/LoginForm.tsx

fix : 소셜로그인 수정
